### ISSUE TITLE
Compatibility issue with angel's industries

### ISSUE THREAD

**Issue by WillianGruber** [CJ5-Z/CJsQualityOfLifeResearch01#1]
Hi!

I have an error loading the game in version 1.1.x (latest)

When loading the game, it says:

"Failed to load mods: Error in assignID: ammo-category with name 'laser-turret' does not exist
Source: laserspeeda-1 (technology)"

It asks to disable this mod and angel's industries (with all overhauls on in settings)

Could you please take a look?

**Comment by cj-sz** [comment]
Hello, sorry for the late reply.
I have loaded up only Angel's Industries and its dependencies along with this mod and I am not receiving any errors.
Check to make sure all mods are up-to-date on the most recent version of the game, and let me know if there are any other mods you are running besides Angel's Industries, its dependencies, and this mod.

**Comment by WillianGruber** [comment]
In the start settings for angel's industries, there are some flags for overhauls.... try enabling all overhauls, restart the game, and the problem should arise.

**Comment by cj-sz** [comment]
I see. It's probably a new issue where the game has redefined ammo types in the code. I'll take a look.

**Comment by cj-sz** [comment]
> In the start settings for angel's industries, there are some flags for overhauls.... try enabling all overhauls, restart the game, and the problem should arise.

I found the issue and it's on my end; I forgot to move from 1.0 to 1.1 when checking for the issue. Will be working on a fix now. Apologies!

**Comment by cj-sz** [comment]
Before closing;
Issue should be resolved, I have checked with the related mods.
Fix is in https://github.com/CJ5-Z/CJsQualityOfLifeResearch01/releases/tag/v2.1.2
If there are any other problems, please open a new issue; issue #1 now resolved.
